core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    # /core/

    url(r'^$', views.homepage, name='homepage'),

    url(r'^index/$', views.index, name='index'),

    url(r'^aboutus/$', views.aboutus, name='aboutus'),

    # /core/7/
    url(r'^(?P<activity_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^login_user/$', views.login_user, name='login_user'),

    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    #core/7/favorite
    url(r'^(?P<activity_id>[0-9]+)/add_total/$', views.add_total, name='add_total'),
]

glopalv3/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include('core.urls'))
]

core/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Activity(models.Model):
    user = models.ForeignKey(User, default=1)
    taskName = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    #is_complete = models.BooleanField(default=False)
    is_complete = models.IntegerField(default=0)

    def __str__(self):
        return self.taskName + ' - ' + self.category

# class UserProfile(models.Model):
#      user = models.ForeignKey(User, default=1)
#      points = models.CharField(max_length=10)

core/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Activity

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

core/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Activity
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import logout
from django.http import JsonResponse
from django.db.models import Q

def homepage(request):
    return render(request, 'core/homepage.html')

def index(request):
    all_activities = Activity.objects.all()
    return render(request, 'core/index.html', {'all_activities': all_activities})

def aboutus(request):
    return render(request, 'core/aboutus.html')

def detail(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    return render(request, 'core/detail.html', {'activity': activity})

def add_total(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    try:
        activity.is_complete = activity.is_complete + 10
        # else:
        #     activity.is_complete += 0
        activity.save()
    except (KeyError, Activity.DoesNotExist):
        return JsonResponse({'success':0})
    else:
        all_activities = Activity.objects.all()
        return redirect('http://127.0.0.1:8000/core/index/') #{'all_activities': all_activities})



class UserFormView(View):
    form_class = UserForm
    template_name = 'core/registration_form.html'

# display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form })

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

             user = form.save(commit=False)

             # cleaned (normlaized) data
             username = form.cleaned_data['username']
             password = form.cleaned_data['password']
             user.set_password(password)
             user.save()

             # returns User objects if credentials are correct
             user = authenticate(username=username, password=password)

             if user is not None:

                 if user.is_active:
                     login(request, user)
                     return redirect('core:index')

        return render(request, self.template_name, {'form': form })

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_activities = Activity.objects.all()
                #all_activities = Activity.objects.filter(user=request.user)
                return redirect('http://127.0.0.1:8000/core/index/')
            else:
                return render(request, 'core/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'core/login.html', {'error_message': 'Invalid login'})
    return render(request, 'core/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('http://127.0.0.1:8000/core/')

core/templates/core/aboutus.html
{% extends 'core/base.html' %}

{% load staticfiles %}
{% block href %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/aboutus.css' %}">
{% endblock %}

{% block title%}About Us{% endblock %}

{% block body %}


  <section id="topInfo">
    <h1>ABOUT OUR TEAM</h1>
    <img id="groupPicture" src="{% static 'core/images/group2.jpg' %}"></img>
    <p id="bio1">Hi, we're Nadean, Pawandeep, Annika, and Nisha. We're from the Girls Who Code program at Synchrony Financial in Chicago.
      We created this project to help users become more environmentally active in an interactive way. We hope our network helps
      bring awareness to simple ways that people can reduce their carbon footprint and waste.
    </p>
    <br>
  </section>


  <section id="allbios">
  <div class="ourBios">
    <img src="{% static 'core/images/nadeanhead.jpg' %}" id="headshot">
    <h2>NADEAN GHOULEH</h2>
    <p class="left">Hey it's Nadean, I am currently a junior at Universal school. I honestly joined Girls Who Code to try something new and meet new people, which I did. The best part about the program was interacting with everyone. Some activities I enjoy are engaging in outdoor activities, spending time with family and friends, drawing, and reading. I appreciate everyone who encouraged me to get involved with Girls Who Code, it was truly a great experience. </p>
  </div>
    <br>
  <div class="ourBios">
    <img src="{% static 'core/images/pawandeephead.jpg' %}" id="headshot">
    <h2>PAWANDEEP KAUR</h2>
    <p class="left">Hey guys I'm Pawandeep and I'm a senior at Waukegan High School. During school, I'm involved in many extracurriculars like JROTC, tennis, National Honor Society, and a lot more. Outside of school, I love to read books, watch YouTubers, TV shows, hang out with friends and listen to music.
    Shoutout to Girls Who Code for this great opportunity. This program was great, and in the words of my brother "yee boi". </p>
  </div>
    <br>
  <div class="ourBios">
    <img src="{% static 'core/images/annikahead.jpg' %}" id="headshot">
    <h2>ANNIKA LAFYATIS</h2>
    <p class="left">I'm Annika, and I'm a senior at Conant High School. My favorite language is Python and my favorite animal is the cat. Besides coding, I enjoy reading,
    spending time with friends, writing for my school newspaper, and playing soccer. Thank you to my teachers and family who have encouraged my interest in computer science.
    I wouldn't have wanted to spend my summer any other way.</p>
  </div>
    <br>
  <div class="ourBios">
    <img src="{% static 'core/images/nishahead.jpg' %}" id="headshot">
    <h2>NISHA PANT</h2>
    <p class="left">Hey! I'm Nisha, a junior at Conant High School. I am interested in web design and back-end development. When I'm not programming, you can find me running, taking photos, reading, trying new foods and listening to music. I plan to pursue computer science in college. </p>
  </div>
  </section>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Glo-Pal{% endblock %}</title>
  {% load staticfiles %}
  <meta charset="UTF-8">
  {% block href %}

  {% endblock %}
  <link href="https://fonts.googleapis.com/css?family=Lato|Source+Sans+Pro:300" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <div id="navbar">
    <a href="{% url 'core:register' %}">SIGN UP</a>
    <a href="{% url 'core:login_user' %}">LOG IN</a>
    <a href="{% url 'core:homepage' %}">HOME</a>
    <a href="{% url 'core:aboutus' %}">ABOUT US</a>
    <a href="{% url 'core:logout_user' %}">LOG OUT</a>
  </div>
  <br>
  <br>
  <br>
  {% block body %}
  {% endblock %}
</body>
</html>

core/templates/core/detail.html
{% extends 'core/base.html' %}

{% block title%}{{ activity }}{% endblock %}

{% block body %}
  {{ activity }}
{% endblock %}

core/templates/core/form_template.html
{% for field in form %}
    <div class="form-group">
        <label class="col-sm-2">{{ field.label_tag }}</label>
        <br><br><br>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

core/templates/core/homepage.html
<!DOCTYPE html>

<html>
<head>

  <title>glo-pal</title>
  {% load staticfiles %}
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'core/homepage.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Lato|Source+Sans+Pro:300" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="{% static 'core/js/homepage.js' %}"></script>
</head>

<body>
  <div id="navbar">
    <a href="{% url 'core:register' %}">SIGN UP</a>
    <a href="{% url 'core:login_user' %}">LOG IN</a>
    <a href="{% url 'core:homepage' %}">HOME</a>
    <a href="{% url 'core:aboutus' %}">ABOUT US</a>
    <a href="{% url 'core:logout_user' %}">LOG OUT</a>
  </div>
  <section id="name">
    <p><i class="fa fa-angle-left" aria-hidden="true" id="left" onclick="goBack()"></i>        gl<i class="fa fa-globe" aria-hidden="true"></i>-pal       <i class="fa fa-angle-right" aria-hidden="true" id="right" onclick="goForward()"></i></p>
  </section>
  <footer>MADE WITH <i class="fa fa-heart" aria-hidden="true"></i> AT CHICAGO GIRLSWHOCODE</footer>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome, User{% endblock %}
{% load staticfiles %}
<!-- {% load mathfilters %} -->
{% block href %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/userhomepage.css' %}">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock %}

{% block body %}

  <h1 id="name">Welcome, {{ user.username }}</h1>

      <div id="all_content">
            {% for activity in all_activities %}
                <div class= "task">
                    <div>
                        <div class="caption">
                            <!-- <h3>{{ activity.taskName }} : {{ activity.is_complete }} points </h3> -->
                            <!-- <h4>{{ activity.category }}</h4> -->

                            <!-- View Details -->
                            <!-- <a href="{% url 'core:detail' activity.id %}" class="btn btn-primary btn-sm" role="button">View Details</a> -->

                            <!-- Favorite activity -->
                            <a href="{% url 'core:add_total' activity.id %}" class="btn btn-primary custom"role="button">
                              <i class="fa fa-pagelines leaf" aria-hidden="true"></i><br>
                                <b>{{ activity.taskName }}</b> <br>
                                {{ activity.is_complete }} points
                                <!-- <span class="{% if activity.is_complete > 0 %}active{% endif %}"></span> -->
                            </a>

                        </div>
                    </div>
                </div>
                <!-- {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %} -->
            {% endfor %}
      </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}
{% load staticfiles %}
{% block href %} <link rel="stylesheet" type="text/css" href="{% static 'core/login.css' %}"> {% endblock %}

{% block body %}
<br>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default loginMain">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'core:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'core:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

core/templates/core/registration_form.html
{% extends 'core/base.html' %}

{% block title %}Register{% endblock %}
{% load staticfiles %}
{% block href %} <link rel="stylesheet" type="text/css" href="{% static 'core/login.css' %}"> {% endblock %}

{% block body %}
<br>
<div class="container-fluid">
  <div class="row loginMain">
      <div class="col-sm-12 col-md-7">
          <div class="panel panel-default">
              <div class="panel-body">
                <h3>Register a New Account:</h3>
                  <form class="form-horizontal" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% include 'core/form_template.html' %}
                      <br><br><br><br><br><br>
                      <div class="form-group center">
                          <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-success">Submit</button>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}